version: "3.4"

services:
  foo-tests:
    build: .
    environment:
      AUT_BROWSERNAME: ${AUT_BROWSERNAME:-chrome}
      APP_ENV: ${APP_ENV:-integration-test}
    depends_on:
      - chrome
      - firefox
  chrome:
    image: selenium/node-chrome:4.0.0
    shm_size: 512mb
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_MAX_CONCURRENT_SESSIONS=2
    ports:
      - "3901:5900"
  firefox:
    image: selenium/node-firefox:4.0.0
    shm_size: 512mb
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_MAX_CONCURRENT_SESSIONS=2
    ports:
      - "3902:5900"
  selenium-hub:
    image: selenium/hub:4.0.0
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"