FROM mcr.microsoft.com/dotnet/sdk:5.0

ENV APP_ENV=integration-test
ENV AUT_USEREMOTEHOST=true

WORKDIR /usr/src

COPY . ./

RUN chmod +x /usr/src/run-tests.sh
RUN dotnet restore

CMD /bin/sh /usr/src/run-tests.sh