version: "3.4"

services:
  web-tests:
    build: .
    environment:
      AUT_BROWSERNAME: ${AUT_BROWSERNAME:-chrome}
      APP_ENV: ${APP_ENV:-integration-test}
    depends_on:
      - chrome
      - firefox
  chrome:
    image: selenium/node-chrome:4.0.0
    shm_size: 512mb
    depends_on:
      - selenium-hub
    env_file: node-env.env
    ports:
      - "3901:5900"
  firefox:
    image: selenium/node-firefox:4.0.0
    shm_size: 512mb
    depends_on:
      - selenium-hub
    env_file: node-env.env
    ports:
      - "3902:5900"
  selenium-hub:
    image: selenium/hub:4.0.0
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"